### ISSUE TITLE
what if i want to use the --playlist-start 

### ISSUE THREAD

**Issue by MoazMirza-13** [mrblomblo/yt-dlp-usage-script#4]
i am trying to download a lot.  and I want to use the option `--playlist-start`  in your setup, can you provide insights ?

**Comment by mrblomblo** [comment]
Please look at the documentation before making an issue, as this information can be found in the customization section (https://github.com/mrblomblo/yt-dlp-usage-script?tab=readme-ov-file#customization).

But to answer your question, place it in the relevant extra args section in VARS.txt.
